# Generated by Django 4.2.13 on 2024-07-30 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_user_managers_remove_user_username"),
    ]

    operations = [
        migrations.AddField(
            model_name="registration",
            name="is_verified",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="registration",
            name="otp",
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name="registration",
            name="otp_expiry",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
