# Generated by Django 4.2.13 on 2024-08-02 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="schedule",
            name="deleted",
            field=models.BooleanField(default=False),
        ),
    ]
